package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

const (
	sourcePackage   = "gin"
	generatedHeader = "// Code generated by integrationexportgen; DO NOT EDIT.\n"
)

var exportFiles = []exportFileSpec{
	{name: "api_export.go"},
	{name: "component_export.go", includeGFLogger: true},
	{name: "error_export.go"},
	{name: "facade_export.go"},
}

var targetPackages = []string{"beego", "chi", "echo", "fiber", "gf", "hertz", "kratos"}

type exportFileSpec struct {
	name            string
	includeGFLogger bool
}

type targetSpec struct {
	packageName     string
	includeGFLogger bool
}

func main() {
	for _, exportFile := range exportFiles {
		source, err := os.ReadFile(exportFile.name)
		if err != nil {
			fail("read canonical "+exportFile.name, err)
		}

		for _, packageName := range targetPackages {
			target := targetSpec{
				packageName:     packageName,
				includeGFLogger: exportFile.includeGFLogger && packageName == "gf",
			}
			output, err := render(source, target)
			if err != nil {
				fail("render "+packageName+" "+exportFile.name, err)
			}

			targetPath := filepath.Join("..", packageName, exportFile.name)
			if err = writeIfChanged(targetPath, output); err != nil {
				fail("write "+targetPath, err)
			}
		}
	}
}

// render creates one framework export file from a Gin canonical source. render 根据 Gin 标准源生成单个框架导出文件。
func render(source []byte, target targetSpec) ([]byte, error) {
	text := string(source)
	packageClause := "package " + sourcePackage
	packageIndex := strings.Index(text, packageClause)
	if packageIndex < 0 {
		return nil, fmt.Errorf("canonical package clause %q not found", packageClause)
	}

	// Drop source-only author and go:generate comments. 丢弃仅属于标准源的作者和 go:generate 注释。
	text = generatedHeader + text[packageIndex:]
	var err error
	text, err = replaceExactlyOnce(text, packageClause, "package "+target.packageName)
	if err != nil {
		return nil, err
	}

	if target.includeGFLogger {
		text, err = addGFLoggerExports(text)
		if err != nil {
			return nil, err
		}
	}

	formatted, err := format.Source([]byte(text))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}
	return formatted, nil
}

// addGFLoggerExports preserves the GoFrame-specific logger aliases. addGFLoggerExports 保留 GoFrame 专用日志别名。
func addGFLoggerExports(text string) (string, error) {
	replacements := [][2]string{
		{
			"\t\"github.com/Zany2/dtoken-go/com/log/dlog\"\n",
			"\t\"github.com/Zany2/dtoken-go/com/log/dlog\"\n\tgflog \"github.com/Zany2/dtoken-go/com/log/gf\"\n",
		},
		{
			"\tLogger                     = dlog.Logger\n",
			"\tLogger                     = dlog.Logger\n\tGFLogger                   = gflog.GFLogger\n",
		},
		{
			"\tNewLoggerWithConfig            = dlog.NewLoggerWithConfig\n",
			"\tNewLoggerWithConfig            = dlog.NewLoggerWithConfig\n\tNewGFLogger                    = gflog.NewGFLogger\n",
		},
	}

	var err error
	for _, replacement := range replacements {
		text, err = replaceExactlyOnce(text, replacement[0], replacement[1])
		if err != nil {
			return "", err
		}
	}
	return text, nil
}

func replaceExactlyOnce(text, old, replacement string) (string, error) {
	if count := strings.Count(text, old); count != 1 {
		return "", fmt.Errorf("replacement anchor occurs %d times: %q", count, old)
	}
	return strings.Replace(text, old, replacement, 1), nil
}

func writeIfChanged(path string, output []byte) error {
	current, err := os.ReadFile(path)
	if err == nil && string(current) == string(output) {
		return nil
	}
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	return os.WriteFile(path, output, 0o644)
}

func fail(action string, err error) {
	_, _ = fmt.Fprintf(os.Stderr, "integrationexportgen: %s: %v\n", action, err)
	os.Exit(1)
}
